apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: registration
spec:
  replicas: 3
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
      - name: nginx
        image: rvsivadocker/orange:1.0
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: myregistrykey